[tool.poetry]
name = "ekans"
version = "0.1.0"
description = "🐍 Ekans"
authors = ["Julien Andreu <julienandreu@me.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
fastapi = "^0.110.0"
uvicorn = "^0.27.1"
psutil = "^5.9.8"

[tool.poetry.group.dev.dependencies]
prospector = { extras = ["with-everything"], version = "^1.10.3" }
mypy = "^1.8.0"
pylint = "^3.0.3"
pyright = "^1.1.350"
ruff = "^0.2.1"
types-psutil = "^5.9.5.20240106"
black = "^24.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.mypy]
python_version = "3.12"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_return_any = true
warn_unreachable = true
strict_optional = true
strict = true

[tool.pylint]
max-line-length = 88
disable = ["C0111", "R0903"]
good-names = ["i", "j", "k", "ex", "Run", "_", "pk", "id"]

[tool.ruff]
line-length = 88
target-version = "py312"
select = ["E", "F", "B", "I", "N", "UP", "PL", "RUF"]
ignore = []

[tool.ruff.mccabe]
max-complexity = 10

[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
^/docs
'''
preview = true
